export const POSTS_LOADED_SUCCESS = "POSTS_LOADED_SUCCESS";
export const POSTS_LOADED_FAIL = "POSTS_LOADED_FAIL";
export const CREATE_POST = "CREATE_POST";

export const POSTLIKE_SUCCESS = "POSTLIKE_SUCCESS";
export const POSTUNLIKE_SUCCESS = "POSTUNLIKE_SUCCESS";

export const SHOW_LOGIN_PANEL = "SHOW_LOGIN_PANEL";

export const POSTSBYID_LOADED_SUCCESS = "POSTSBYID_LOADED_SUCCESS";

export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

export const SHOW_FULL_POST = "SHOW_FULL_POST";
export const HIDE_FULL_POST = "HIDE_FULL_POST";

export const UPDATE_CART = "UPDATE_CART";
